### ISSUE TITLE
Problem with preCompile.js

### ISSUE THREAD

**Issue by smr-mohammadzadeh** [hphamid/maktabkhooneh-imdb-server#1]
Hi. When I try to run "node preCompile.js" in cmd, it reports this error:
`$ node preCompile.js
D:\Maktab\maktabkhooneh-imdb-server-master\maktabkhooneh-imdb-server-master\src\
annotationSystem\ModuleScanner.js:21
    var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                                ^

TypeError: Cannot read property '1' of null
    at getFunctionArgs (D:\Maktab\maktabkhooneh-imdb-server-master\maktabkhooneh
-imdb-server-master\src\annotationSystem\ModuleScanner.js:21:65)
    at D:\Maktab\maktabkhooneh-imdb-server-master\maktabkhooneh-imdb-server-mast
er\src\annotationSystem\ModuleScanner.js:52:36
    at D:\Maktab\maktabkhooneh-imdb-server-master\maktabkhooneh-imdb-server-mast
er\src\node_modules\annotation-parser\index.js:23:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_conte
xt.js:53:3)
`

**Comment by hphamid** [comment]
Hi

There was a problem with "getFunctionArgs" method in ModuleScanner. Problem fixed.

Thank you for reporting the issue.
